export const locations = [
  {
    id: "1",
    Geo_Name: "Velacheri",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "2",
    Geo_Name: "Medavakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "3",
    Geo_Name: "Ashok Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "4",
    Geo_Name: "Anna Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "5",
    Geo_Name: "Kodungaiyur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "6",
    Geo_Name: "Kovilambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "7",
    Geo_Name: "Alapakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "8",
    Geo_Name: "Kelambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "9",
    Geo_Name: "Chitlapakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "10",
    Geo_Name: "Puzhal",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "11",
    Geo_Name: "Pallavaram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "12",
    Geo_Name: "Arumbakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "13",
    Geo_Name: "Ponniammanmedu",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "14",
    Geo_Name: "Kolathur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "15",
    Geo_Name: "T Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "16",
    Geo_Name: "Tharamani",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "17",
    Geo_Name: "Perambur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "18",
    Geo_Name: "Tambaram East",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "19",
    Geo_Name: "Thiruverkadu",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "20",
    Geo_Name: "Akkarai",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "21",
    Geo_Name: "K K Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "22",
    Geo_Name: "K K Nagar West",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "23",
    Geo_Name: "Surapet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "24",
    Geo_Name: "Neelankarai",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "25",
    Geo_Name: "Nanganallur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "26",
    Geo_Name: "Kodambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "27",
    Geo_Name: "Vandalur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "28",
    Geo_Name: "Padur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "29",
    Geo_Name: "Iyyappanthangal",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "30",
    Geo_Name: "Valasarvakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "31",
    Geo_Name: "Thiruvanmiyur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "32",
    Geo_Name: "Ambattur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "33",
    Geo_Name: "Porur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "34",
    Geo_Name: "Mudichur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "35",
    Geo_Name: "Ayapakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "36",
    Geo_Name: "Injambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "37",
    Geo_Name: "Kundrathur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "38",
    Geo_Name: "Vyasarpadi",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "39",
    Geo_Name: "Adyar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "40",
    Geo_Name: "Thirunindravur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "41",
    Geo_Name: "Choolaimedu",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "42",
    Geo_Name: "Broadway",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "43",
    Geo_Name: " Besant Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "44",
    Geo_Name: "Tharamani",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "45",
    Geo_Name: "Purasawalkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "46",
    Geo_Name: "Adambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "47",
    Geo_Name: "Thiruvottiyur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "48",
    Geo_Name: "Paruthipet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "49",
    Geo_Name: "Virugambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "50",
    Geo_Name: "Mylapore",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "51",
    Geo_Name: "Anna Nagar East",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "52",
    Geo_Name: "Villivakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "53",
    Geo_Name: "Aynamabakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "54",
    Geo_Name: "Sholinganallur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "55",
    Geo_Name: "Maduravoyal",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "56",
    Geo_Name: "Mathur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "57",
    Geo_Name: "Mandaveli",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "58",
    Geo_Name: "Madambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "59",
    Geo_Name: "Mugalivakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "60",
    Geo_Name: "Tambaram West",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "61",
    Geo_Name: "Pudupet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "62",
    Geo_Name: "Veperi",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "63",
    Geo_Name: "George Town",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "64",
    Geo_Name: "Teynampet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "65",
    Geo_Name: "Guindy",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "66",
    Geo_Name: "Palavakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "67",
    Geo_Name: "Perungudi",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "68",
    Geo_Name: "Korukkupet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "69",
    Geo_Name: "KK Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "70",
    Geo_Name: "Redhills",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "71",
    Geo_Name: "Perungulathur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "72",
    Geo_Name: "Selaiyur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "73",
    Geo_Name: "Guduvancheri",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "74",
    Geo_Name: "Pallikarnai",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "75",
    Geo_Name: "Pattabiram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "76",
    Geo_Name: "Tambaram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "77",
    Geo_Name: "Madupakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "78",
    Geo_Name: "Kalpakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "79",
    Geo_Name: "Maraimalai Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "81",
    Geo_Name: "Chromepet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "81",
    Geo_Name: "Kellys",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "82",
    Geo_Name: "Nungambakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "83",
    Geo_Name: "Jafferkhanpet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "84",
    Geo_Name: "West Mambalam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "85",
    Geo_Name: "Santhome",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "86",
    Geo_Name: "Anna Nagar West Extension",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "87",
    Geo_Name: "Rpyapuram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "88",
    Geo_Name: "Moulivakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "89",
    Geo_Name: "Narayanapuram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "90",
    Geo_Name: "Abhiramapuram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "91",
    Geo_Name: "Manali",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "92",
    Geo_Name: "Madhavaram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "93",
    Geo_Name: "Korattur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "95",
    Geo_Name: "Madhanandapuram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "96",
    Geo_Name: "Iyappanthangal",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "98",
    Geo_Name: "CIT Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "99",
    Geo_Name: "Uthandi",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "100",
    Geo_Name: "Raja Annamalaipuram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "101",
    Geo_Name: "Kilpauk",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "102",
    Geo_Name: "Shenoy Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "103",
    Geo_Name: "Ayanavaram",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "104",
    Geo_Name: "Saligramam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "105",
    Geo_Name: "Vadapalani",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "106",
    Geo_Name: "St Thomas Mount",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "107",
    Geo_Name: "Mogappair",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "108",
    Geo_Name: "Mogappair West",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "109",
    Geo_Name: "Tambaram Sanatorium",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "110",
    Geo_Name: "Madipakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "111",
    Geo_Name: "Pammal",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "112",
    Geo_Name: "Sirucheri",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "113",
    Geo_Name: "Chinmaya Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "114",
    Geo_Name: "Vepery",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "115",
    Geo_Name: "Periyar Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "116",
    Geo_Name: "Sithalapakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "117",
    Geo_Name: "Pozhichalur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "118",
    Geo_Name: "Sembakkam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "119",
    Geo_Name: "MR Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "120",
    Geo_Name: "Wimco Nagar",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "121",
    Geo_Name: "Koyambedu",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "122",
    Geo_Name: "Manimangalam",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "123",
    Geo_Name: "Kovur",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "124",
    Geo_Name: "Thirumullaivayal",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "125",
    Geo_Name: "Pallikaranai",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "126",
    Geo_Name: "Mount Road",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "127",
    Geo_Name: "Aminjikarai",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "128",
    Geo_Name: "Thousand Lights",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "129",
    Geo_Name: "Tondiarpet",
    Geo_Head: "33",
    Geo_City: "42",
  },
  {
    id: "130",
    Geo_Name: "Karungalpalayam",
    Geo_Head: "33",
    Geo_City: "42",
  },
];
